baseURL = "https://jeremy-wayland.me/"
languageCode = "en-us"
theme = "custom-hugo-theme"

# Plugins
[params.plugins]

# CSS Plugins
[[params.plugins.css]]
URL = "css/main.css"
[[params.plugins.css]]
URL = "css/rad-icons.css"
[[params.plugins.css]]
URL = "css/custom.css"

# JS Plugins
[[params.plugins.js]]
URL = "js/rad-animations.js"
[[params.plugins.js]]
URL = "js/sticky-header.js"
[[params.plugins.js]]
URL = "js/library/fontfaceobserver.js"


# navigation
[menu]


[[menu.header]]
name = "Education"
URL = "#education"
weight = 2

[[menu.header]]
name = "Experience"
URL = "#experience"
weight = 3

[[menu.header]]
name = "Hobbies"
URL = "#about"
weight = 5

[[menu.header]]
name = "Projects"
URL = "#projects"
weight = 4

[[menu.header]]
name = "Contact"
URL = "#contact"
weight = 6


[[menu.footer]]
name = "Education"
URL = "#education"
weight = 2

[[menu.footer]]
name = "Experience"
URL = "#experience"
weight = 3

[[menu.footer]]
name = "Hobbies"
URL = "#about"
weight = 5

[[menu.footer]]
name = "Projects"
URL = "#projects"
weight = 4

[[menu.footer]]
name = "Contact"
URL = "#contact"
weight = 6

[params]

sections = [
  "showcase",
  "education",
  "experience",
  "project",
  "about",
  "contact",
]

googleTagManagerID = "GTM-000000" # Google Analytics works with Google Tag Manager
homepageExperienceCount = 6

[params.logo]
text1 = "Jeremy"
text2 = "Wayland"

[params.footer]
copyright = "Custom theme, built from © Adritian."
[params.footer.radity_logo]
x = "img/general/design-and-code-radity.png"
_2x = "img/general/design-and-code-radity@2x.png"
alt = "Design & Code - Radity"
